### ISSUE TITLE
setPermission probably doesn't work, WDA stops

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium-ios-simulator#189]
https://github.com/appium/appium-ios-simulator/pull/188

## Scenario
- https://github.com/appium/ruby_lib_core/pull/160

```ruby
@@driver.execute_script('mobile: setPermission', {service: 'calendar', state: 'yes', bundleId: 'com.apple.mobilecal'})
@@driver.activate_app('com.apple.mobilecal')
```

## Env
- xcuitest-driver 2.100.0 (set the version by manual)
- ios-simulator 3.7.0
- Appium master
- iOS 11.4 emulator

## 1. `UnknownError` happened after calling `setPermission`
After calling setPermission, simulator probably restarted and WDA stopped. `.app_installed?('com.apple.mobilecal')` worked but commands needs WDA didn't.

```
[HTTP] --> POST /wd/hub/session/b5e6736f-db76-411e-9603-3fac0d64db3e/appium/device/activate_app
[HTTP] {"bundleId":"com.apple.mobilecal"}
[debug] [W3C (b5e6736f)] Calling AppiumDriver.activateApp() with args: ["com.apple.mobilecal",null,null,null,"b5e6736f-db76-411e-9603-3fac0d64db3e"]
[debug] [XCUITest] Executing command 'activateApp'
[debug] [JSONWP Proxy] Proxying [POST /wda/apps/launch] to [POST http://localhost:8100/session/FCC17AF5-FA0A-428A-BC9C-7FD419FD4CD8/wda/apps/launch] with body: {"bundleId":"com.apple.mobilecal"}
[JSONWP Proxy] Got an unexpected response: {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[debug] [W3C (b5e6736f)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8100
[debug] [W3C (b5e6736f)]     at /Users/kazuaki/GitHub/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:236:13
[debug] [W3C (b5e6736f)]     at Generator.throw (<anonymous>)
[debug] [W3C (b5e6736f)]     at asyncGeneratorStep (/Users/kazuaki/GitHub/appium/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
[debug] [W3C (b5e6736f)]     at _throw (/Users/kazuaki/GitHub/appium/node_modules/@babel/runtime/helpers/asyncToGenerator.js:29:9)
[debug] [W3C (b5e6736f)]     at <anonymous>
[HTTP] <-- POST /wd/hub/session/b5e6736f-db76-411e-9603-3fac0d64db3e/appium/device/activate_app 500 16 ms - 832
[HTTP]
```

So, should we make sure WDA running after the command?

## ~~2. "unset" after allow permission by manual (The returned value only depends on `setPermission` command)~~

I allowed a permission for calrndar after launching 'com.apple.mobilecal' by manual. The returned value was _unset_.

```
)> @@driver.execute_script('mobile: getPermission', {service: 'calendar',bundleId: 'com.apple.mobilecal'})
=> "unset"
```

## ~~3. `setPermission` doesn't work?~~
Launch calendar app after allowing permission like below, the permission dialog appeared. I think the dialog shouldn't appear.

<img src="https://user-images.githubusercontent.com/5511591/48239073-db9e6280-e410-11e8-8e66-5f03892f94e1.png" width=500>

---

I guess the change is inspired by https://github.com/wix/AppleSimulatorUtils .
I've used the command line tool in my environment. I've handled permissions before starting Appium session. (I have another CLI to create/delete simulators. I call AppleSimulatorUtils in it.) Then, the permission commands work well.

**Comment by KazuCocoa** [comment]
@mykola-mokhnach 
Thanks and sorry, the current logic worked as same as #190 . My scenario was wrong...
(So, the 2 and 3 in the description was my bad.)
https://github.com/appium/ruby_lib_core/pull/160/files#diff-642294321e09de07e102867a6bd7e804R18 is fixed version.

**Comment by KazuCocoa** [comment]
Resetting simulator happens in both way. So, we need to re-connect WDA session after this.

**Comment by mykola-mokhnach** [comment]
So there are two question?

- Does the previous implementation (direct access to TCC) work the same as one, that uses WIX tools?
- restarting the springboard service also resets WDA?

**Comment by KazuCocoa** [comment]
> Does the previous implementation (direct access to TCC) work the same as one, that uses WIX tools?

Yes.

> restarting the springboard service also resets WDA?

Yes. For example, after setPermission, below error happened. 

```
@@driver.switch_to.alert.text
Selenium::WebDriver::Error::UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8100
from UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8100
```

Even `@@driver.execute_script('mobile: getPermission', {service: 'calendar',bundleId: 'com.example.apple-samplecode.UICatalog'})` worked. (Since the getPermission worked for simulator directly.

**Comment by mykola-mokhnach** [comment]
> Yes. For example, after setPermission, below error happened.

This means it will be necessary to remove setPermission mobile command and move it to capabilities, so we can set permissions before WDA init. getPermissions can be kept though.

Thanks for your assistance

**Comment by KazuCocoa** [comment]
Exactly :+1:

**Comment by dpgraham** [comment]
I think having it as a capability is a better approach anyway.
