### ISSUE TITLE
isShutdown() not working

### ISSUE THREAD

**Issue by KostromaAleksey** [appium/appium-ios-simulator#293]
https://github.com/appium/appium-ios-simulator/blob/75a8a212fc587fbc717c71ceff798193a4ec947c/lib/simulator-xcode-6.js#L407

The result is always 'false', because [e.stderr == undefined], use [e.toString()] or another correct property.

Appium: 1.18.2
MacOS: 10.13.6
Xcode: 10.1
Node: 12.18.4

**Comment by mykola-mokhnach** [comment]
```
_.includes(undefined, 'yolo') === false
_.includes(null, 'yolo') === false
_.includes('y', 'yolo') === true
```

IMHO everything works as expected

**Comment by KostromaAleksey** [comment]
But, e contains: (Error running 'getenv': An error was encountered processing the command (domain = com.apple.CoreSimulator.SimError, code = 164):
Unable to getenv ("dummy") while not booting or booted. Current state: Shutdown)

e.stderr returns undefined, and the result is false, although it should have been true.

This error resulted in the inability to start the simulator in headless mode (isHeadless = true).

Once again, I get:
e = Error running 'getenv': An error was encountered processing the command (domain = com.apple.CoreSimulator.SimError, code = 164):
Unable to getenv ("dummy") while not booting or booted. Current state: Shutdown

e. stderr = undefined

e.toString() = e = Error running 'getenv': An error was encountered processing the command (domain = com.apple.CoreSimulator.SimError, code = 164):
Unable to getenv ("dummy") while not booting or booted. Current state: Shutdown

**Comment by mykola-mokhnach** [comment]
Try appium@beta. The fact e.stderr is undefined is due to a bug in `node-simctl` dependency.

**Comment by KostromaAleksey** [comment]
Yes, there is no bug in appium 1.19.0-beta.0.

Thanks for the support!
