### ISSUE TITLE
Error: Appium - iOS Simulator -[WD Proxy] connect ECONNREFUSED 127.0.0.1:8080

### ISSUE THREAD

**Issue by prachuryasahoo** [appium/appium-ios-simulator#297]
Hi Team,

I am getting the error([WD Proxy] connect ECONNREFUSED 127.0.0.1:8080) while executing my appium script.

**Configuration:**
Appium version: 1.8.0 ( Have also tried 1.8.1/2)
Xcode version: 11.7
iOS platform version: 13.7
MacOS version: Catalina(10.15.7)

**Capabilities:**
[debug] [BaseDriver]   "alwaysMatch": {
[debug] [BaseDriver]     "platformName": ["iOS",](url)
[debug] [BaseDriver]     "appium:unicodeKeyboard": "true",
[debug] [BaseDriver]     "appium:resetKeyboard": "true",
[debug] [BaseDriver]     "appium:platformVersion": "13.7",
[debug] [BaseDriver]     "appium:deviceName": "iPhone11Pro",
[debug] [BaseDriver]     "appium:deviceOrientation": "portrait",
[debug] [BaseDriver]     "appium:appiumVersion": "1.18.0",
[debug] [BaseDriver]     "appium:app": "/Users/automation/Project/testapp/newTestApp/Build/Products/Debug-iphonesimulator/newTestApp.app",
[debug] [BaseDriver]     "appium:name": "RobotAppiumiOS",
[debug] [BaseDriver]     "appium:showXcodeLog": "true",
[debug] [BaseDriver]     "appium:useNewWDA": "false",
[debug] [BaseDriver]     "appium:waitForQuiescence": "false",
[debug] [BaseDriver]     "appium:showIOSLog": "true",
[debug] [BaseDriver]     "appium:automationName": "XCUITest",
[debug] [BaseDriver]     "appium:iosInstallPause": "2000",
[debug] [BaseDriver]     "appium:wdaStartupRetries": "2",
[debug] [BaseDriver]     "appium:wdaStartupRetryInterval": "15000",
[debug] [BaseDriver]     "appium:wdaLocalPort": "8080",
[debug] [BaseDriver]     "appium:shouldUseSingletonTestManager": "false"
[debug] [BaseDriver]   }

appium-doctor stats:

Digitals-Mini:~ digitalautomation$ appium-doctor --ios
info AppiumDoctor Appium Doctor v.1.15.4
info AppiumDoctor ### Diagnostic for necessary dependencies starting ###
info AppiumDoctor  ✔ The Node.js binary was found at: /usr/local/bin/node
info AppiumDoctor  ✔ Node version is 15.0.1
info AppiumDoctor  ✔ Xcode is installed at: /Applications/Xcode.app/Contents/Developer
info AppiumDoctor  ✔ Xcode Command Line Tools are installed in: /Applications/Xcode.app/Contents/Developer
info AppiumDoctor  ✔ DevToolsSecurity is enabled.
info AppiumDoctor  ✔ The Authorization DB is set up properly.
info AppiumDoctor  ✔ Carthage was found at: /usr/local/bin/carthage. Installed version is: 0.36.0
info AppiumDoctor  ✔ HOME is set to: /Users/automation
info AppiumDoctor ### Diagnostic for necessary dependencies completed, no fix needed. ###
info AppiumDoctor 
info AppiumDoctor ### Diagnostic for optional dependencies starting ###
WARN AppiumDoctor  ✖ opencv4nodejs cannot be found.
WARN AppiumDoctor  ✖ ffmpeg cannot be found
WARN AppiumDoctor  ✖ mjpeg-consumer cannot be found.
WARN AppiumDoctor  ✖ set-simulator-location is not installed
WARN AppiumDoctor  ✖ idb and idb_companion are not installed
WARN AppiumDoctor  ✖ applesimutils cannot be found
info AppiumDoctor  ✔ ios-deploy is installed at: /usr/local/bin/ios-deploy. Installed version is: 1.11.3
info AppiumDoctor ### Diagnostic for optional dependencies completed, 6 fixes possible. ###
info AppiumDoctor 
info AppiumDoctor ### Optional Manual Fixes ###
info AppiumDoctor The configuration can install optionally. Please do the following manually:
WARN AppiumDoctor  ➜ Why opencv4nodejs is needed and how to install it: https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/image-comparison.md
WARN AppiumDoctor  ➜ ffmpeg is needed to record screen features. Please read https://www.ffmpeg.org/ to install it
WARN AppiumDoctor  ➜ mjpeg-consumer module is required to use MJPEG-over-HTTP features. Please install it with 'npm i -g mjpeg-consumer'.
WARN AppiumDoctor  ➜ set-simulator-location is needed to set location for Simulator. Please read https://github.com/lyft/set-simulator-location to install it
WARN AppiumDoctor  ➜ Why idb is needed and how to install it: https://github.com/appium/appium-idb
WARN AppiumDoctor  ➜ Why applesimutils is needed and how to install it: http://appium.io/docs/en/drivers/ios-xcuitest/
info AppiumDoctor 
info AppiumDoctor ###
info AppiumDoctor 
info AppiumDoctor Bye! Run appium-doctor again when all manual fixes have been applied!
info AppiumDoctor 

Kindly help.

**Comment by prachuryasahoo** [comment]
Complete Logs:
[Appium_Error_Logs.txt](https://github.com/appium/appium-ios-simulator/files/5432572/Appium_Error_Logs.txt)

**Comment by KazuCocoa** [comment]
What happen when you run below command?

```
[debug] [W3C] /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -derivedDataPath /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent -destination id=9717068F-24C9-48CA-94FF-0CC105CAF636 IPHONEOS_DEPLOYMENT_TARGET=13.7 GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO
```

**Comment by prachuryasahoo** [comment]
Hi @KazuCocoa,

Thanks for your response.

I am getting the below error : 

Testing failed:
	WebDriverAgentRunner:
		WebDriverAgentRunner-Runner.app (1862) encountered an error (Failed to create a bundle instance representing '/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest'. Check that the bundle exists on disk.)

** TEST EXECUTE FAILED **

I can confirm the bundle does exist in the said location.

Digitals-Mac-mini:appium-webdriveragent digitalautomation$ cd build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app/PlugIns/
Digitals-Mac-mini:PlugIns digitalautomation$ ls
**WebDriverAgentRunner.xctest**
Digitals-Mac-mini:PlugIns digitalautomation$ 

Also tried to build and test the WebDriverAgent.xcodeproj in Xcode but no luck. Getting the same error.

Thanks.

**Comment by KazuCocoa** [comment]
I guess your command failed to create proper files because of permission issue.
We recommend not to install appium as sudo, but I guess yours were installed as sudo. (since your module is in `/usr/local/lib/node_modules/appium`)

> Make sure you have not installed Node or Appium with sudo, otherwise you'll run into problems).

http://appium.io/docs/en/about-appium/getting-started/

Could you fix the permission for the appium directory?

**Comment by prachuryasahoo** [comment]
Hi @KazuCocoa , Thanks for your response.

I used the below command to install appium:
_npm install -g appium_ 
For installing some of the dependencies (Ex: ios-deploy , ideviceinstaller) i used homebrew commands.

**Comment by KazuCocoa** [comment]
It seems you built npm (node) environment as root permission. So, `npm install -g appium` was also installed as root.
Common solutions are building node env without root or you can also change your local permission in `/usr/local/lib/node_modules/appium`. You can google both ways.

**Comment by prachuryasahoo** [comment]
Hi @KazuCocoa ,

I have uninstalled appium and node from my system.
Then installed node : brew install node

Now, when I am trying to install appium, I am getting the below error:

npm install -g appium
npm notice 
npm notice New patch version of npm available! 7.0.3 -> 7.0.5
npm notice Changelog: https://github.com/npm/cli/releases/tag/v7.0.5
npm notice Run npm install -g npm@7.0.5 to update!
npm notice 
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /usr/local/lib/node_modules/appium/node_modules/.bin/authorize-ios
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/appium/node_modules/.bin/authorize-ios'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/digitalautomation/.npm/_logs/2020-10-24T23_15_20_672Z-debug.log

Do you know what causes this NOENT error?

Thanks

**Comment by prachuryasahoo** [comment]
Uninstalled node that was installed using brew and reinstalled using NodeJs installer. This error is resolved. 
However, I am still getting the error when trying to build the test app:

**Testing failed:**
	WebDriverAgentRunner:
WebDriverAgentRunner-Runner.app (7152) encountered an error (Failed to create a bundle instance representing '/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest'. Check that the bundle exists on disk.)

**Comment by prachuryasahoo** [comment]
Issue has been Resolved

Error :
WebDriverAgentRunner-Runner.app (7152) encountered an error (Failed to create a bundle instance representing '/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/**Build**/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest'. Check that the bundle exists on disk.)

Resolution:
Navigate to the directory: cd /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent
Rename **b**uild to **B**uild : mv build Build
